### ISSUE TITLE
Two feature requests

### ISSUE THREAD

**Issue by dmland** [LucBennett/BetterUnsubscribe#1]
First of all, thank you for this extremely useful add-on.

I have two suggestions, which I entered in my review, but I'm not sure that will reach you.

1. Option to delete emails by matching just the address (e.g., vote@candidate-name.us), instead of the full RFC 5322 name-address, (e.g., "Elect Candidate Now!" &lt;vote@candidate-name.us&gt;). Political campaigns and brands routinely change the display-name so each deletion currently matches only one email out of dozens with the same address.
2. After deleting emails, please dismiss the dialog, because the email for which you opened it doesn't even exist any more.

**Comment by LucBennett** [comment]
Thank you for your kind words and thoughtful suggestions, they're much appreciated! I'm glad you find the add-on useful.

I wanted to share an update on your requests:

1. **Dismissing the dialog after unsubscribing/deleting**: I’ve implemented this change, and the dialog will now dismiss automatically once the action is completed. Thanks for pointing this out, it’s a great usability improvement!

2. **Deleting emails by matching address, name-address, or domain**: I’ve added support for this! You’ll now be able to delete emails through various matching methods: by the full name-address combination, just the address, or by domain. Implementing this was more challenging than anticipated due to some limitations in the Thunderbird API, but I’m happy to report that it’s working now.

To accommodate these changes, I’ve had to redesign the HTML popup UI to add the additional buttons and options. I’m still experimenting with different designs to make it intuitive and efficient. Once I settle on a layout that I’m happy with, I plan to release an updated version of the add-on.

Thanks again for your feedback, it’s been incredibly helpful in improving BetterUnsubscribe. Feel free to share any additional thoughts or suggestions!

**Comment by LucBennett** [comment]
I have released these changes (and more) in the new version 2.7.0. Please update to the latest version and let me know what you think!

**Comment by dmland** [comment]
I noticed the changes and kind of forgot that I'd requested them. I use the selective deletion feature all the time.

Thanks again!
